### ISSUE TITLE
Что если упростить?

### ISSUE THREAD

**Issue by coursar** [akhrorov/up-down#4]
https://github.com/akhrorov/up-down/blob/be756736c51cc35bf27df7c873219386b0b32513/src/js/app.js#L50-L54

```js
purchasesList.insertBefore(purchaseListEl, purchaseListEl.previousElementSibling); 
```

Будет ли работать вот так? Если да, то почему?

**Comment by akhrorov** [comment]
нет, без return правильно работать не будет потому что когда блок if становиться true мы должны выйти из функции а без return он будет читать дальше.
